### PR TITLE
appveyor CI

### PR DESCRIPTION
**Pull request by chcg**
- added appveyor.yml CI build config
- update to vs2013 similar to current n++ (available as free community release) with platform vs120_xp to still support winxp sp3, removed VS2008 VS configs
- enabled multiprocessor builds

, see https://ci.appveyor.com/project/chcg/jstoolnpp/build/1.20.2.4

appveyor.yml  could be extended for automatic deployment to github on tagging, see e.g. https://github.com/pnedev/compare-plugin/releases

### CODE REVIEW

**Comment by sunjw** [comment]
@chcg Really thanks for this PR. 
I'll consider merge this into a new branch later (maybe next week or later). Because I'm preparing my new dev computer, my old one is broken. I have no usable dev env now, sorry for this delay.

**Comment by chcg** [comment]
You still have to register your project at appveyor to take advantage of the additional CI build.

**Comment by sunjw** [comment]
@chcg I am consider migrating JSToolNpp to vs2015. So I'll do more on CI after I decided which way to go in future of this project.

**Comment by chcg** [comment]
Note: The appveyor build is also building with platform toolset v140_xp aka VS2015. So I would expect no issues with that. The only drwaback I've seen with vs2015 is the bigger dll size compared to vs2013, e.g. 
https://ci.appveyor.com/project/chcg/jstoolnpp/build/1.20.2.4/job/l6qunh98rn0kyu8v/artifacts
300KB
vs:
https://ci.appveyor.com/project/chcg/jstoolnpp/build/1.20.2.4/job/m9xmq86689wryon8/artifacts
279KB

**Comment by sunjw** [comment]
Got, thanks.

**Pull request merged**
